### ISSUE TITLE
General Inquirer Lexicon

### ISSUE THREAD

**Issue by JJery-web** [ben-aaron188/r_helper_functions#2]
Dear experts,
Hello!

I am a beginner of text analysis. Recently, I want to use general inquirer for content analysis. But I found that
http://www.wjh.harvard.edu/ ~inquirer/inqdict.txt is not accessible.

However, I found that your GitHub website has attached the corresponding **dictionary**(https://raw.githubusercontent.com/ben-aaron188/r_helper_functions/master/lcm/inquireraugmented.csv), which makes me very excited. But by checking the CSV file of general inquirer, I found that there were some symbols with "#" in it, which confused me. For example:
**HAPPY#1
HAPPY#2
HAPPY#3
HAPPY#4**

What do these #1, #2, #3, #4 mean?

Ilook forward to your reply! thank you

**Comment by ben-aaron188** [comment]
Hi - Thanks for reaching out. The definitive answer will be in the docs/publications on the General Inquirer. But a short one here: when there are several "meanings" of a word, these are listed as separate entries. E.g. the entry for "about" nicely shows this.
It's tricky to automatically disambiguate which version maps to a given input sequence but you may not even need it and just go with the most used "meaning" of the word.
